#!/bin/sh

#set -e

_DISTRIBUTION="ascii"
_ARCHITECTURES="amd64"
_LINUX_FLAVOURS="amd64"
_ARCHIVE_AREAS="main contrib non-free"
_SOURCE="false"
_DEVUAN_INSTALLER="live"

_MIRROR_BINARY="http://deb.devuan.org/merged"
_INSTALLER_MIRROR="http://packages.devuan.org/merged"

lb config noauto \
	--mode devuan \
	--clean \
	--chroot-filesystem "squashfs" \
	--initsystem "sysvinit" \
	--bootloaders "syslinux,grub-efi" \
	--distribution "${_DISTRIBUTION}" \
	--debian-installer-distribution "${_DISTRIBUTION}" \
	--debian-installer "${_DEVUAN_INSTALLER}" \
	--debian-installer-gui "true" \
	--architectures "${_ARCHITECTURES}" \
	--linux-flavours "${_LINUX_FLAVOURS}" \
	--apt-recommends "false" \
	--apt-secure "true" \
	--apt-indices "false" \
	--apt-source-archives "false" \
	--archive-areas "${_ARCHIVE_AREAS}" \
	--parent-mirror-bootstrap "${_MIRROR_BINARY}" \
	--parent-mirror-binary "${_MIRROR_BINARY}" \
	--mirror-bootstrap "${_MIRROR_BINARY}" \
	--mirror-binary "${_MIRROR_BINARY}" \
    --parent-mirror-debian-installer "${_INSTALLER_MIRROR}" \
    --mirror-debian-installer "${_INSTALLER_MIRROR}" \
    --firmware-chroot "false" \
	--iso-application "DIY Linux" \
	--iso-publisher "DIY" \
	--iso-volume "DIY Live" \
	--backports "false" \
	--security "false" \
	--updates "false" \
	--memtest "none" \
	--win32-loader "false" \
	--debug \
	--verbose \
	--source "false" \
	--bootappend-live "boot=live config components file=/preseed.cfg quiet splash autologin nouveau.modeset=0 radeon.modeset=0" \
"${@}"
