#!/bin/bash
#diy User Set-up

set -e

USER=$1

if [ ! -d "/home/$USER/.config/diy" ]; then
	mkdir /home/$USER/.config/diy
fi

if [ ! -f "/home/$USER/.config/diy/diy-setup" ]; then

    if [ -f "/home/$USER/.gtkrc-2.0" ]; then
        rpl -q 'REPLACEME' $USER /home/$USER/.gtkrc-2.0 > /dev/null 2>&1
    fi
    if [ -f "/home/$USER/.mozilla/firefox/cpffssvb.default/prefs.js" ]; then
        rpl -q 'REPLACEME' $USER /home/$USER/.mozilla/firefox/cpffssvb.default/prefs.js > /dev/null 2>&1
    fi

    ln -s /usr/share/backgrounds /home/$USER/images/wallpapers/shared

    if [ "$USER" != "diylive" ]; then
		sed -i".bak" '/<!-- installer start -->/,/<!-- installer end -->/d' /etc/skel/.config/jwm/menu
		rm /etc/skel/.config/jwm/menu.bak
		if [ -f "/home/$USER/.config/jwm/menu" ]; then
			rm /home/$USER/.config/jwm/menu
		fi
		cp /etc/skel/.config/jwm/menu /home/$USER/.config/jwm/menu
		
		rpl -q '# policykit-1-gnome' '/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &' /etc/skel/.config/jwm/autostart > /dev/null 2>&1
		cp /etc/skel/.config/jwm/autostart /home/$USER/.config/jwm/autostart
	fi
	
    #~ if [ "$USER" != "diylive" ]; then
		#~ sed -i".bak" '/<!-- installer start -->/,/<!-- installer end -->/d' /etc/skel/.jwmrc
		#~ rm /etc/skel/.jwmrc.bak
		#~ if [ -f "/home/$USER/.jwmrc" ]; then
			#~ rm /home/$USER/.jwmrc
		#~ fi
		#~ cp /etc/skel/.jwmrc /home/$USER/.jwmrc
	#~ fi

	touch /home/$USER/.config/diy/diy-setup
    chown -R $USER:$USER /home/$USER
fi

xdg-user-dirs-update

exit 0
